## 1
GET localhost:8080/hello/coffee2
Content-Type: application/json

#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Wed, 18 Oct 2023 05:23:31 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#coffee hello!
#
#Response code: 200; Time: 87ms (87 ms); Content length: 13 bytes (13 B)

## 2
GET localhost:8080/hello2/amond
Content-Type: application/json

#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Set-Cookie: JSESSIONID=EE8635E3D917580EAF8791309E8E9EF0; Path=/; HttpOnly
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 12
#Date: Wed, 18 Oct 2023 05:27:46 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#amond hello!
#
#Response code: 200; Time: 82ms (82 ms); Content length: 12 bytes (12 B)

## 3
GET localhost:8080/hello/coffee2
Content-Type: application/json

#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: JSESSIONID=EE8635E3D917580EAF8791309E8E9EF0
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 14
#Date: Wed, 18 Oct 2023 05:30:22 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#coffee2 hello!
#
#Response code: 200; Time: 8ms (8 ms); Content length: 14 bytes (14 B)

## 4 (위에 요청 내역 지운 상태에서 테스트 해봄: 세션담은 해더 요청 나감)
GET localhost:8080/hello/coffee3
Content-Type: application/json

#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: JSESSIONID=EE8635E3D917580EAF8791309E8E9EF0
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 14
#Date: Wed, 18 Oct 2023 05:31:46 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#coffee3 hello!
#
#Response code: 200; Time: 4ms (4 ms); Content length: 14 bytes (14 B)

## 5 (100s 이후에 테스트 해보았는데, request header 에 jsession 살아있었다..!,, 서버에서 바뀌는 설정)
GET localhost:8080/hello/amond5
Content-Type: application/json

#GET http://localhost:8080/hello/amond5
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: JSESSIONID=EE8635E3D917580EAF8791309E8E9EF0
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Wed, 18 Oct 2023 05:37:50 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#amond5 hello!
#
#Response code: 200; Time: 10ms (10 ms); Content length: 13 bytes (13 B)
#

## 6
GET localhost:8080/hello2/amond6
Content-Type: application/json

#GET http://localhost:8080/hello2/amond6
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: JSESSIONID=EE8635E3D917580EAF8791309E8E9EF0
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Set-Cookie: JSESSIONID=854A88E1D41116B05AFFC03664C70085; Path=/; HttpOnly
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Wed, 18 Oct 2023 05:40:24 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#amond6 hello!
#
#Response code: 200; Time: 12ms (12 ms); Content length: 13 bytes (13 B)
#
#2023-10-18 14:27:46.362  INFO 5348 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : 2 session: org.apache.catalina.session.StandardSessionFacade@1c4c26a4
#2023-10-18 14:27:46.362  INFO 5348 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : EE8635E3D917580EAF8791309E8E9EF0
#org.apache.catalina.connector.RequestFacade@160c9965
#org.apache.catalina.connector.RequestFacade@160c9965
#org.apache.catalina.connector.RequestFacade@160c9965
#org.apache.catalina.connector.RequestFacade@160c9965
#2023-10-18 14:40:24.756  INFO 5348 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : 2 session: org.apache.catalina.session.StandardSessionFacade@2c1721b7
#2023-10-18 14:40:24.757  INFO 5348 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : 854A88E1D41116B05AFFC03664C70085

#676D9D17DAE08126EFE2E75297005AAB





GET localhost:8080/hello2/1101
Content-Type: application/json

#
#
#GET http://localhost:8080/hello2/1101
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#HTTP/1.1 200
#Set-Cookie: SESSION=YmY0NmI4YTMtZjQ2MC00Y2Y3LWFjMjYtMzlhZDg0OTBiMDVm; Path=/; HttpOnly; SameSite=Lax
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 11
#Date: Tue, 31 Oct 2023 22:50:18 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#1101 hello!
#
#Response code: 200; Time: 126ms (126 ms); Content length: 11 bytes (11 B)



GET localhost:8080/hello2/1101-2
Content-Type: application/json
#
#GET http://localhost:8080/hello2/1101-2
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: SESSION=YmY0NmI4YTMtZjQ2MC00Y2Y3LWFjMjYtMzlhZDg0OTBiMDVm
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#
#
#2023-11-01 07:54:55.030  INFO 11432 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : 2 session: org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSessionWrapper@7fa44fff
#2023-11-01 07:54:56.119  INFO 11432 --- [nio-8080-exec-1] sss.sessiontest.SampleController         : d77ad51f-47dd-4f1f-baab-1ef36bd4ba45
#
#
#HTTP/1.1 200
#Set-Cookie: SESSION=ZDc3YWQ1MWYtNDdkZC00ZjFmLWJhYWItMWVmMzZiZDRiYTQ1; Path=/; HttpOnly; SameSite=Lax
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Tue, 31 Oct 2023 22:56:05 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#1101-2 hello!
#
#Response code: 200; Time: 129118ms (2 m 9 s 118 ms); Content length: 13 bytes (13 B)


GET localhost:8080/hello2/1101-3
Content-Type: application/json


#2023-11-01 08:03:36.194  INFO 11432 --- [nio-8080-exec-2] sss.sessiontest.SampleController         : 2 session: org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSessionWrapper@4163603d
#2023-11-01 08:03:36.194  INFO 11432 --- [nio-8080-exec-2] sss.sessiontest.SampleController         : d77ad51f-47dd-4f1f-baab-1ef36bd4ba45

#GET http://localhost:8080/hello2/1101-3
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: SESSION=ZDc3YWQ1MWYtNDdkZC00ZjFmLWJhYWItMWVmMzZiZDRiYTQ1
#Accept-Encoding: br,deflate,gzip,x-gzip



#
#Response code: 200; Time: 129118ms (2 m 9 s 118 ms); Content length: 13 bytes (13 B)
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Tue, 31 Oct 2023 23:03:59 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#1101-3 hello!
#
#Response code: 200; Time: 81857ms (1 m 21 s 857 ms); Content length: 13 bytes (13 B)

###

GET localhost:8080/hello2/1101-4
Content-Type: application/json

//01 08:15:17.188 DEBUG 11432 --- [nio-8080-exec-3] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to sss.sessiontest.SampleController#sayHello2(String, HttpServletRequest)
//2023-11-01 08:15:17.188  INFO 11432 --- [nio-8080-exec-3] sss.sessiontest.SampleController         : 2 session: org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSessionWrapper@77a36e5f
//2023-11-01 08:15:17.188  INFO 11432 --- [nio-8080-exec-3] sss.sessiontest.SampleController         : d77ad51f-47dd-4f1f-baab-1ef36bd4ba45


#GET http://localhost:8080/hello2/1101-4
#Content-Type: application/json
#Connection: Keep-Alive
#User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.8)
#Cookie: SESSION=ZDc3YWQ1MWYtNDdkZC00ZjFmLWJhYWItMWVmMzZiZDRiYTQ1
#Accept-Encoding: br,deflate,gzip,x-gzip
#
####
#
#HTTP/1.1 200
#Content-Type: text/plain;charset=UTF-8
#Content-Length: 13
#Date: Tue, 31 Oct 2023 23:15:21 GMT
#Keep-Alive: timeout=60
#Connection: keep-alive
#
#1101-4 hello!
#
#Response code: 200; Time: 12289ms (12 s 289 ms); Content length: 13 bytes (13 B)


GET localhost:8080/hello2/1101-4
Content-Type: application/json